version: '3.8'

services:
  nginx:
    build: .
    container_name: nginx_container
    ports:
      - "8080:80"
      - "2222:22"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./html:/usr/share/nginx/html:ro
    restart: always
    stdin_open: true
    tty: true