version: '3.7'
services:
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - backend

  server_1:
    container_name: server_1
    build: ./server
    environment:
      - serverNum=1
    networks:
      - backend

  server_2:
    container_name: server_2
    build: ./server
    environment:
      - serverNum=2
    networks:
      - backend

  server_3:
    container_name: server_3
    build: ./server
    environment:
      - serverNum=3
    networks:
      - backend

networks:
  backend:
    driver: bridge
